ab_task/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from students_marks import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('students_marks.urls')),
]

students_marks/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.add_marks, name='add_marks' ),
    path('leaderboard/', views.leader_board, name = 'leaderboard' ),
]

students_marks/models.py
from django.db import models

# Create your models here.

class marks(models.Model):
    roll_number = models.IntegerField(null=True, blank=True)
    name = models.CharField(max_length=50, blank=True, null=True)
    maths_marks = models.FloatField(null=True, blank=True)
    physics_marks = models.FloatField(null=True, blank=True)
    chemistry_marks = models.FloatField(null=True, blank=True)
    percentage = models.FloatField(null=True, blank=True)
    total = models.FloatField(null=True, blank=True)

students_marks/forms.py
from django.forms.widgets import NumberInput
from .models import marks
from django import forms

class marks_form(forms.Form):
    name = forms.CharField(
        label="Name of the student",
        max_length=50,
        widget=forms.TextInput(attrs = {'class':'form-control', 'required':True, 'placeholder':'Example: Alex'})
    )

    roll_number = forms.IntegerField(
        label="Student Roll Number",
        widget=forms.NumberInput(attrs={'class':'form-control', 'required':True, 'placeholder':'Example: 12345'})
    )

    maths_marks = forms.FloatField(
        label="Marks in Mathematics",
        widget= forms.NumberInput(attrs = {'class':" form-control",'step':0.1, 'required':True, 'placeholder':'Example: 75.25' })
    )

    physics_marks = forms.FloatField(
        label="Marks in Physics",
        widget=forms.NumberInput(attrs={'class':" form-control",'step':0.1, 'required':True, 'placeholder':'Example: 75.25'})
    )

    chemistry_marks = forms.FloatField(
        label="Marks in Chemistry",
        widget=forms.NumberInput(attrs={'class':" form-control",'step':0.1, 'required':True, 'placeholder':'Example: 75.25'})
    )

    def clean_roll_number(self):
        data = self.cleaned_data.get("roll_number")

        if len(str(data)) != 5:
            raise forms.ValidationError("Please Enter a valid Roll Number (5 digit number)")

        return data

    def clean_maths_marks(self):
        data = self.cleaned_data.get("maths_marks")

        if data < 0  or data > 100:
            raise forms.ValidationError("Marks should be in the range 0 - 100")

        return data

    def clean_physics_marks(self):
        data = self.cleaned_data.get("physics_marks")

        if data < 0  or data > 100:
            raise forms.ValidationError("Marks should be in the range 0 - 100")

        return data

    def clean_chemistry_marks(self):
        data = self.cleaned_data.get("chemistry_marks")

        if data < 0  or data > 100:
            raise forms.ValidationError("Marks should be in the range 0 - 100")

        return data

students_marks/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import marks
from .forms import marks_form
from django.contrib import messages

# Create your views here.

def add_marks(request):
    if request.method == "POST":
        form  = marks_form(request.POST)

        if form.is_valid():
            marks_instance = marks.objects.create(name = request.POST['name'], roll_number = int(request.POST['roll_number']), maths_marks = float(request.POST['maths_marks']), physics_marks = float(request.POST['physics_marks']), chemistry_marks = float(request.POST['chemistry_marks']) )
            marks_instance.save()
            marks_instance.total = float(request.POST['maths_marks']) + float(request.POST['physics_marks']) + float(request.POST['chemistry_marks'])
            marks_instance.percentage = round(marks_instance.total/3 , 2)
            marks_instance.save(update_fields = ['total', 'percentage'])
            #print(marks.objects.all())
            form  = marks_form()
            messages.success(request, f'Details added successfully!')
    else:
        form  = marks_form()

    return render(request, 'add_marks.html', {'form':form})
    #return HttpResponse("Add your Marks here!")

def leader_board(request):
    keyword = ""
    if request.method == "POST":
        
        if request.POST['action'] == "sort":
            qset = marks.objects.all().order_by(request.POST['sort_by'])
            if request.POST['sort_by'][0] == "-":
                order_by = request.POST['sort_by'][1:] + " " + "descending"
            else:
                order_by = request.POST['sort_by']

        else:
            qset = marks.objects.filter(name__icontains = request.POST['search']).order_by("-percentage")
            order_by = "percentage"
            keyword = request.POST['search']

    else:
        qset = marks.objects.all().order_by("-percentage")
        order_by = "percentage"

    return render(request, 'leaderboard.html', {'qset':qset,'order_by':order_by, 'keyword':keyword})
    #return HttpResponse("Leader board will be displayed here!")

students_marks/templates/add_marks.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>Students Marks Info - Add Marks</title>
  </head>
  <body style="background-color: whitesmoke;">

    <div>
        {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }} alert-dismissable fade show custom" role = "alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            </div>
        {% endfor %}
        {% endif %}
    </div>
    
    <div class="container mt-5 rounded " style="border-radius: 1em;">
        <div class="card shadow" style="border-radius: 1em;">
            <div class="card-header text-center" >
                <h2>
                    Add Student Details
                </h2>
            </div>
            <div class="card-body">

               <form action=" {% url 'add_marks' %} " class="needs-validation" method="POST" novalidate>
                    {% csrf_token %}

                    <div class="form-group row">
                        <label for="id_name" class="col-sm-3 " style="font-size: large;"   > {{ form.name.label }} </label>
                        <div class="col-sm-8" >
                            {{ form.name }}
                            <div class="invalid-feedback">
                                Name should not be empty!.
                            </div>
                        </div>
                    </div>

                    
                    <div class="form-group row">
                        <label for="id_roll_number" class="col-sm-3 " style="font-size: large;"   > {{ form.roll_number.label }} </label>
                        <div class="col-sm-8" >
                            {{ form.roll_number }}

                            <div class="invalid-feedback">
                                Should not be empty!.
                            </div>

                            {% for error in form.roll_number.errors %}
                            <div class="invalidCheck" style="color: rgb(216, 7, 7); font-size: small;"  >
                                {{ error }} 
                            </div>
                            {% endfor %}
                        </div>
                    </div>

                    <div class="form-group row">
                        <label for="id_maths_marks" class="col-sm-3 " style="font-size: large;"   > {{ form.maths_marks.label }} </label>
                        <div class="col-sm-8" id="maths_marks_field" >
                            {{ form.maths_marks }}


                            <div class="invalid-feedback">
                                Please fill out marks.
                            </div>
                            {% for error in form.maths_marks.errors %}
                            <div class="invalidCheck" style="color: rgb(216, 7, 7); font-size: small;"  >
                                {{ error }} 
                            </div>
                            {% endfor %}
                        </div>
                    </div>


                    <div class="form-group row">
                        <label for="physics_marks_filed" class="col-sm-3 " style="font-size: large;"   > {{ form.physics_marks.label }} </label>
                        <div class="col-sm-8" id="physics_marks_field" >
                            {{ form.physics_marks }}

                            <div class="invalid-feedback">
                                Please fill out marks.
                            </div>

                            {% for error in form.physics_marks.errors %}
                            <div class="invalidCheck" style="color: rgb(216, 7, 7); font-size: small;"  >
                                {{ error }} 
                            </div>
                            {% endfor %}
                        </div>
                    </div>



                    <div class="form-group row">
                        <label for="chemistry_marks_filed" class="col-sm-3 " style="font-size: large;"   > {{ form.chemistry_marks.label }} </label>
                        <div class="col-sm-8" id="chemistry_marks_field" >
                            {{ form.chemistry_marks }}

                            <div class="invalid-feedback">
                                Please fill out marks.
                            </div>

                            {% for error in form.chemistry_marks.errors %}
                            <div class="invalidCheck" style="color: rgb(216, 7, 7); font-size: small;"  >
                                {{ error }} 
                            </div>
                            {% endfor %}
                        </div>
                    </div>


                    <div class="text-center">
                        <button class="btn btn-primary" type="submit">Submit Marks</button>
                    </div>
                </form>
                <p></p>
                <div class="text-center">
                    <a href="{% url 'leaderboard' %}" class="btn btn-primary">View Rankings</a>
                </div>

            </div>
        </div>
    </div>

    
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.2.1.js" crossorigin="anonymous" ></script>



    <script type="text/javascript">

        $(function() {
  
          $(".custom").fadeTo(2000, 500).slideUp(500, function () {
            $(".custom").slideUp(500);
          });
  
        });
  
      </script>


    <script>
        // Example starter JavaScript for disabling form submissions if there are invalid fields
        (function() {
          'use strict';
          window.addEventListener('load', function() {
            // Fetch all the forms we want to apply custom Bootstrap validation styles to
            var forms = document.getElementsByClassName('needs-validation');
            // Loop over them and prevent submission
            var validation = Array.prototype.filter.call(forms, function(form) {
              form.addEventListener('submit', function(event) {
                if (form.checkValidity() === false) {
                  event.preventDefault();
                  event.stopPropagation();
                }
                form.classList.add('was-validated');
              }, false);
            });
          }, false);
        })();
    </script>


  </body>
</html>

students_marks/templates/leaderboard.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">

    <title>Students Marks Info - Leader Board</title>
  </head>
  <body style="background-color: whitesmoke;" >
      <div class="container " style="border-radius: 1em;" >
        <div class="card mt-5 shadow" style="border-radius: 1em;" >
            <div class="card-header">
                <h2 class="text-center" >
                    Student Rankings (Based on {{ order_by }})
                </h2>

                <p class="text-center">
                    <a href="{% url 'add_marks' %}">Add marks of a student</a>
                </p>
            </div>
            <div class="card-body">
                <nav class="navbar navbar-light m-0" >

                    <form class="form-inline" method="POST" action=" {% url 'leaderboard' %} " >
                        {% csrf_token %}
                        <input type="hidden" name="action" value="sort" id="">
                        <select class="form-control mr-sm-2"  id="sort_by" name = 'sort_by' required>
                            <option value="program2" selected disabled> Select Any one </option>
                            <option value="name"> Name (A-Z) </option>
                            <option value="-name"> Name (Z-A) </option>
                            <option value="total"> Total (Ascending) </option>
                            <option value="-total"> Total (Descending) </option>
                            <option value="-maths_marks"> By highest marks in maths</option>
                            <option value="-physics_marks"> By highest marks in physics </option>
                            <option value="-chemistry_marks">By highest marks in chemistry</option>
                        </select>
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Sort</button>
                    </form>

                    <form class="form-inline" method="POST" action=" {% url 'leaderboard' %} " >

                        {% csrf_token %}
                        <input type="hidden" name="action" id="" value="search">
                        <input class="form-control mr-sm-2" type="search" name = "search" placeholder="Search by name" aria-label="Search">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                    </form>
                    
                </nav>

                {% if keyword != "" %}
                <div class="text-center">
                    Showing results for "{{keyword}}"....
                </div>
                {% endif %}

                {% for student in qset %}
                <div class="card " style="border-radius: 1em;">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-sm-2">
                                <h2>
                                    {{ forloop.counter }}
                                </h2>
                                <h6>
                                    Position
                                </h6>
                            </div>
                            <div class="col-sm-10">
                                <div class="d-flex">
                                    <div class="mr-5">
                                        <h5>
                                            Name: {{ student.name }}
                                        </h5>
                                        <h5>
                                            Roll Number: {{ student.roll_number }}
                                        </h5>
                                    </div>
                                    <div class="">
                                        <h5>
                                            Maths: {{ student.maths_marks }}
                                        </h5>
                                        <h5>
                                            Physics: {{ student.physics_marks }}
                                        </h5>
                                        <h5>
                                            Chemistry: {{ student.chemistry_marks }}
                                        </h5>
                                        <h5>
                                            Total: {{ student.total }}
                                        </h5>
                                        <h5>
                                            Percentage: {{ student.percentage }}
                                        </h5>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <p></p>
                {% endfor %}
                
            </div>

        </div>
        <p></p>
      </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>

  </body>
</html>